- id: sign-commit
  name: Sign commit
  description: "Hashes some fields of the commit and adds a signature for verification by other systems"
  entry: sign-commit
  language: ruby
  language_version: 2.7.2
  pass_filenames: true
  minimum_pre_commit_version: 0.15.4
  stages:
  - commit-msg
