- id: sign-commit
  name: Sign commit
  description: "Hashes some fields of the commit and adds a signature for verification by other systems"
  entry: sign-commit
  language: ruby
  language_version: 3.2.2
  pass_filenames: true
  minimum_pre_commit_version: 3.0.0
  stages:
    - commit-msg
